apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 labels:
   app: backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
     - name: flask-backend
       image:abishatk/flask-app
       imagePullPolicy: Never
       ports:
       - containerPort: 8800
    