version: "3.9"
services:
  server:
    build:  ./api
    ports: 
    - "8800:8800"
    volumes: 
    - ./api:/app
    environment: 
      FLASK_ENV: development
  web:
    build: ./my-app 
    ports: 
      - "3000:3000"
    volumes: 
      - ./my-app:/user/src/app
    depends_on: 
      - server
