apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  selector:
    app: app-frontend
  ports:
    - port: 3000
      nodePort: 30000
      protocol: TCP
      targetPort: 3000
  type: NodePort